# Generated by Django 5.0.1 on 2024-01-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(default=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=25, null=True)),
                ('image', models.ImageField(blank=True, default='def.jpg', null=True, upload_to='images/')),
                ('addres', models.TextField(blank=True, default='Male', max_length=200)),
            ],
        ),
    ]
