# Generated by Django 5.0.1 on 2024-01-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='addres',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
