# Generated by Django 5.0.1 on 2024-01-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_human_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='addres',
            new_name='address',
        ),
    ]
