# Generated by Django 5.0.1 on 2024-01-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_addres_human_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to='images/'),
        ),
    ]
